  spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?user=postgres.yrbloybnxfnsvhjwjfjm&password=gUiGuI#08410
      driver-class-name: org.postgresql.Driver

